services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: kivo
      MYSQL_DATABASE: kivo_cloud
    ports:
      - '3307:3306'
    volumes:
      - kivo_cloud_mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  kivo_cloud_mysql:
