CREATE TABLE IF NOT EXISTS trial_registry (
  machine_id_hash VARCHAR(64) NOT NULL PRIMARY KEY,
  company_uuid VARCHAR(36) NOT NULL,
  claimed_at TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
